### PR TITLE
Feature/DBLP abstract extraction

### PR DESCRIPTION
**Pull request by xkopenreview**
this pr should add a static function extractAbstract to Tools function to extract abstract and pdf based on the html of the dblp note which will be invoked by process function of DBLP.org/-/Record and DBLP.org/-/Abstract.

### CODE REVIEW

**Comment by carlosmondra** [comment]
I'm of the idea that maybe this change should have been created in a different library. Something like `@openreview/tools`. But I guess for now this is fine.

**Comment by xkopenreview** [comment]
looks like dl.acm.org can auto detect umass ip so pdf can be retrieved running the test in my local but not in github actions

**Comment by melisabok** [comment]
> looks like dl.acm.org can auto detect umass ip so pdf can be retrieved running the test in my local but not in github actions
existing dblp papers from dl.acm.org which run through meta-extraction does not have pdf so it's not some function that is missing

why would you need to extract the PDF? we only need the link to the PDF.

**Comment by xkopenreview** [comment]
> > looks like dl.acm.org can auto detect umass ip so pdf can be retrieved running the test in my local but not in github actions
> > existing dblp papers from dl.acm.org which run through meta-extraction does not have pdf so it's not some function that is missing
> 
> why would you need to extract the PDF? we only need the link to the PDF.

correct. i mean the pdf link, not the pdf file

**Comment by melisabok** [comment]
> correct. i mean the pdf link, not the pdf file

so the page that contains the link has a pay wall?

**Review by melisabok — APPROVED** [review]

**Comment by xkopenreview** [comment]
some statistics of existing dblp imports in v1
the count includes doi.org redirections (redirection from doi.org to another domain and redirection from doi.org to another doi.org address then to another domain) there are also 36728 imports without html

for 90% coverage, the following domains should be handled by a domain specific rule or the general rule
```
ieeexplore.ieee.org
arxiv.org
link.springer.com
dl.acm.org
linkinghub.elsevier.com
aclanthology.org
proceedings.mlr.press
www.aaai.org
www.aclweb.org
openaccess.thecvf.com
papers.nips.cc
ojs.aaai.org
onlinelibrary.wiley.com
www.mdpi.com
www.ijcai.org
aclweb.org
proceedings.neurips.cc
```

for 95% coverage, the following domains should be handled by a domain specific rule or the general rule
```
ieeexplore.ieee.org
arxiv.org
link.springer.com
dl.acm.org
linkinghub.elsevier.com
aclanthology.org
proceedings.mlr.press
www.aaai.org
www.aclweb.org
openaccess.thecvf.com
papers.nips.cc
ojs.aaai.org
onlinelibrary.wiley.com
www.mdpi.com
www.ijcai.org
aclweb.org
proceedings.neurips.cc
epubs.siam.org
openreview.net
portal.acm.org
academic.oup.com
aclanthology.info
www.medra.org
aaai.org
www.isca-speech.org
drops.dagstuhl.de
www.isca-archive.org
proceedings.spiedigitallibrary.org
www.worldscientific.com
www.scitepress.org
www.lrec-conf.org
www.tandfonline.com
direct.mit.edu
www.jstage.jst.go.jp
```

---
full list of domain and count
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/xukun/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/xukun/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>



Domain | Count
-- | --
ieeexplore.ieee.org | 277810
arxiv.org | 212235
link.springer.com | 122821
dl.acm.org | 87427
linkinghub.elsevier.com | 51830
aclanthology.org | 16428
proceedings.mlr.press | 13764
www.aaai.org | 12821
www.aclweb.org | 11313
openaccess.thecvf.com | 11229
papers.nips.cc | 10696
ojs.aaai.org | 8014
onlinelibrary.wiley.com | 6733
www.mdpi.com | 6546
www.ijcai.org | 5842
aclweb.org | 5585
proceedings.neurips.cc | 5488
epubs.siam.org | 4891
openreview.net | 4263
portal.acm.org | 3786
academic.oup.com | 3394
aclanthology.info | 3370
www.medra.org | 3090
aaai.org | 2886
www.isca-speech.org | 2740
drops.dagstuhl.de | 2619
www.isca-archive.org | 2454
proceedings.spiedigitallibrary.org | 2341
www.worldscientific.com | 2282
www.scitepress.org | 2085
www.lrec-conf.org | 2068
www.tandfonline.com | 1947
direct.mit.edu | 1724
www.jstage.jst.go.jp | 1641
eprint.iacr.org | 1587
diglib.eg.org | 1530
www.usenix.org | 1458
www.hindawi.com | 1413
www.bmva.org | 1344
ijcai.org | 1285
doi.ieeecomputersociety.org | 1234
bmcbioinformatics.biomedcentral.com | 1206
journals.sagepub.com | 1180
www.inderscience.com | 1058
jmlr.org | 1018
hdl.handle.net | 979
pubsonline.informs.org | 959
www.cambridge.org | 883
www.frontiersin.org | 879
dx.plos.org | 795
dslpitt.org | 760
mindmodeling.org | 732
services.igi-global.com | 721
www.spiedigitallibrary.org | 691
knowledge.amia.org | 636
eccc.weizmann.ac.il | 597
dl.gi.de | 594
tel.archives-ouvertes.fr | 538
www.roboticsproceedings.org | 506
jair.org | 466
asp-eurasipjournals.springeropen.com | 459
www.nature.com | 402
eudl.eu | 398
electronicimaging.spiedigitallibrary.org | 396
journal.sepln.org | 375
aisel.aisnet.org | 359
www.degruyter.com | 354
www.liebertpub.com | 340
www.jsjkx.com | 333
www.ndss-symposium.org | 317
www.emerald.com | 314
journal.frontiersin.org | 306
pubs.acs.org | 287
search.ieice.org | 282
ebooks.iospress.nl | 257
library.imaging.org | 254
openproceedings.org | 251
bmcmedinformdecismak.biomedcentral.com | 246
jwcn-eurasipjournals.springeropen.com | 233
www2003.org | 231
transacl.org | 229
ethos.bl.uk | 223
bmvc2022.mpi-inf.mpg.de | 221
www.nowpublishers.com | 218
content.iospress.com | 216
ietresearch.onlinelibrary.wiley.com | 215
www.escholarship.org | 214
editions-rnti.fr | 209
peerj.com | 209
ojs.academypublisher.com | 208
petsymposium.org | 203
eccc.hpi-web.de | 200
datasets-benchmarks-proceedings.neurips.cc | 188
asistdl.onlinelibrary.wiley.com | 178
www.fujipress.jp | 169
www.crcnetbase.com | 168
www.asso-aria.org | 163
ercim-news.ercim.eu | 158
zenodo.org | 155
bmcsystbiol.biomedcentral.com | 153
www.ipol.im | 153
www.ingentaconnect.com | 148
d-nb.info | 147
crpit.scem.westernsydney.edu.au | 147
www.dropbox.com | 142
digital-library.theiet.org | 141
nbn-resolving.org | 139
ceur-ws.org | 137
www.booksonline.iospress.nl | 137
jivp-eurasipjournals.springeropen.com | 134
cogsci.mindmodeling.org | 132
itiis.org | 132
joss.theoj.org | 131
doi.acm.org | 128
easychair.org | 125
www.ams.org | 125
www.jair.org | 121
www.oldcitypublishing.com | 113
www.rfc-editor.org | 113
appliednetsci.springeropen.com | 108
sol.sbc.org.br | 107
www.atlantis-press.com | 104
acl-bg.org | 101
www.cys.cic.ipn.mx | 99
ksiresearchorg.ipage.com | 99
iopscience.iop.org | 98
www.iis.sinica.edu.tw | 94
www.jcomputers.us | 94
wires.onlinelibrary.wiley.com | 94
pnas.org | 94
www.vldb.org | 90
jcheminf.biomedcentral.com | 88
tacl2013.cs.columbia.edu | 87
www.itiis.org | 86
theoryofcomputing.org | 83
lmcs.episciences.org | 83
lib.jucs.org | 81
ria.revuesonline.com | 78
epjdatascience.springeropen.com | 76
jbiomedsem.biomedcentral.com | 75
joi.jlc.jst.go.jp | 74
www.ep.liu.se | 72
proceedings.mlsys.org | 71
www.science.org | 71
asmp-eurasipjournals.springeropen.com | 70
www.combinatorics.org | 69
proceedings.kr.org | 69
www.acl-bg.org | 69
www.igi-global.com | 68
cys.cic.ipn.mx | 68
www.internetmathematicsjournal.com | 67
www.actapress.com | 65
bmcmedimaging.biomedcentral.com | 65
www.mitpressjournals.org | 64
doiserbia.nb.rs | 61
jivp.eurasipjournals.com | 59
koreascience.or.kr | 59
hal.archives-ouvertes.fr | 58
www.esann.org | 58
repository.isls.org | 54
www.intlpress.com | 53
jgaa.info | 53
journal-bcs.springeropen.com | 52
kilthub.cmu.edu | 51
www.cinc.org | 51
www.informatica.si | 50
opg.optica.org | 49
journals.flvc.org | 49
www.cai.sk | 47
www.vde-verlag.de | 46
www.rintonpress.com | 46
www.jocm.us | 45
journalprivacyconfidentiality.org | 45
www.ijsi.org | 41
aimsciences.org | 41
shonan.nii.ac.jp | 40
isi.revuesonline.com | 39
tches.iacr.org | 39
univagora.ro | 39
searchworks.stanford.edu | 38
scidok.sulb.uni-saarland.de | 38
www.journals.cambridge.org | 38
jise.iis.sinica.edu.tw | 37
www.jucs.org | 37
journalofbigdata.springeropen.com | 36
quantum-journal.org | 36
drive.google.com | 35
jasss.soc.surrey.ac.uk | 35
www.sciendo.com | 35
www.scirp.org | 35
ewic.bcs.org | 34
wscg.zcu.cz | 34
dn.revuesonline.com | 34
arc.aiaa.org | 34
conference.iiis.tsinghua.edu.cn | 33
www.linguamatica.com | 33
colt2010.haifa.il.ibm.com | 33
dad.uni-bielefeld.de | 33
biodatamining.biomedcentral.com | 33
journals.cambridge.org | 32
eatcs.org | 32
mr.crossref.org | 32
workshop-proceedings.icwsm.org | 32
autosoftjournal.net | 32
atala.org | 31
www.ijimai.org | 31
almob.biomedcentral.com | 31
fedcsis.org | 31
ijvr.eu | 31
www.dlib.org | 30
www.akbc.ws | 30
www.scholarpedia.org | 30
www.scs-europe.net | 30
www.taylorfrancis.com | 30
www.cs.mcgill.ca | 29
repositum.tuwien.at | 29
ist.publisher.ingentaconnect.com | 28
openurl.ingenta.com | 28
jlm.ipipan.waw.pl | 28
www.kuenstliche-intelligenz.de | 27
opac.bncf.firenze.sbn.it | 27
publikationen.sulb.uni-saarland.de | 27
asmedigitalcollection.asme.org | 27
journalofcloudcomputing.springeropen.com | 27
jis-eurasipjournals.springeropen.com | 27
infoscience.epfl.ch | 27
dh2016.adho.org | 26
iai-uiserv1.iai.fzk.de | 26
septentrio.uit.no | 26
jocg.org | 26
www.polibits.cidetec.ipn.mx | 25
online-journals.org | 25
cybersecurity.springeropen.com | 25
spiedigitallibrary.org | 25
www.jbiomedsem.com | 24
tsi.revuesonline.com | 24
academiccommons.columbia.edu | 24
isyou.info | 24
braininformatics.springeropen.com | 24
ci.nii.ac.jp | 23
journal.r-project.org | 23
trec.nist.gov | 22
sites.computer.org | 22
www.isa-afp.org | 22
www.digitalhumanities.org | 22
dh2020.adho.org | 22
caiac.pubpub.org | 22
compass.onlinelibrary.wiley.com | 22
jips-k.org | 22
www.oegai.at | 21
eprints-phd.biblio.unitn.it | 21
iajit.org | 21
www.academypublisher.com | 21
itc.ktu.lt | 21
dh2018.adho.org | 20
ts.revuesonline.com | 20
journals.riverpublishers.com | 20
openlib.tugraz.at | 20
www.ccsenet.org | 20
www.complex-systems.com | 19
dmtcs.episciences.org | 19
annals-csis.org | 19
journals.uic.edu | 19
vciba.springeropen.com | 19
graphicsinterface.org | 19
polibits.cidetec.ipn.mx | 18
cyber.bibl.u-szeged.hu | 18
www.kybernetika.cz | 18
linguamatica.com | 18
journal.ub.tu-berlin.de | 18
www.jvrb.org | 17
handle.unsw.edu.au | 17
www.ub.uni-heidelberg.de | 17
tuprints.ulb.tu-darmstadt.de | 17
www.scpe.org | 17
ksiresearch.org | 17
ascelibrary.org | 17
www.techscience.com | 17
journals.tubitak.gov.tr | 17
www.tdp.cat | 16
amsdottorato.unibo.it | 16
library.cuhk.edu.hk | 16
aaltodoc.aalto.fi | 16
firstmonday.org | 16
www.jstatsoft.org | 16
etd.adm.unipi.it | 15
idl.iscram.org | 15
dcpapers.dublincore.org | 15
www.atala.org | 15
jisajournal.springeropen.com | 15
asmp.eurasipjournals.com | 15
edoc.ub.uni-muenchen.de | 14
bera-journals.onlinelibrary.wiley.com | 14
www.jot.fm | 14
www.cs.rpi.edu | 13
dharchive.org | 13
www.online-journals.org | 13
conference.scipy.org | 13
bmcgenomics.biomedcentral.com | 13
transactions.ismir.net | 13
hcjournal.org | 13
mitpress.mit.edu | 12
www.mifav.uniroma2.it | 12
opus.kobv.de | 12
cs.anu.edu.au | 12
www.biomedcentral.com | 12
jdmdh.episciences.org | 12
scienceopen.com | 12
www.epjdatascience.com | 12
jes.eurasipjournals.com | 12
scfbm.biomedcentral.com | 12
fieldrobotics.net | 12
www.jscires.org | 12
www.dirf.org | 11
www.minas.medellin.unal.edu.co | 11
www.graphicsinterface.org | 11
publications.rwth-aachen.de | 11
opus4.kobv.de | 11
www.icwsm.org | 11
isca-speech.org | 11
web1.bib.uni-hildesheim.de | 11
hss.ulb.uni-bonn.de | 11
journal.acs.org.au | 11
publikationen.uni-tuebingen.de | 11
cit.srce.unizg.hr | 11
www.riverpublishers.com | 11
www.thieme-connect.de | 11
bsb-eurasipjournals.springeropen.com | 11
bsb.eurasipjournals.com | 11
coria.asso-aria.org | 11
alife-robotics.org | 11
datascience.codata.org | 11
www.aimsciences.org | 11
www.annualreviews.org | 11
lirias.kuleuven.be | 10
www.aes.org | 10
resolver.tudelft.nl | 10
www.worldcat.org | 10
collegepublications.co.uk | 10
digbib.ubka.uni-karlsruhe.de | 10
www.stringology.org | 10
www.gatsby.ucl.ac.uk | 10
www.ifets.info | 10
huji-primo.hosted.exlibrisgroup.com | 10
www.dr.hut-verlag.de | 10
objet.revuesonline.com | 10
seer.ufrgs.br | 10
dr | 9
ojs.bibsys.no | 9
www.irit.fr | 9
satassociation.org | 9
www.crcpress.com | 9
bioinformatics.oupjournals.org | 9
etheses.whiterose.ac.uk | 9
seer.lcc.ufmg.br | 9
WWW.CQVIP.COM | 9
www.ceas.cc | 9
www.easychair.org | 9
www.jsoftware.us | 9
www.rairo-ita.org | 9
jis.eurasipjournals.com | 9
revistas.unab.edu.co | 9
www.jamris.org | 9
freidok.uni-freiburg.de | 8
c3.ndc.nasa.gov | 8
urn.kb.se | 8
xtf-prod.stanford.edu | 8
math.colgate.edu | 8
www.ronpub.com | 8
librarysearch.library.utoronto.ca | 8
www.w3.org | 8
darwin.bth.rwth-aachen.de | 8
www.springerlink.com | 8
ecp.ep.liu.se | 8
www.sciedupress.com | 8
219.238.6.200 | 8
www.rairo-ro.org | 8
cdr.lib.unc.edu | 8
bridges.monash.edu | 8
sebd2012.dei.unipd.it | 7
jise.org | 7
cjtcs.cs.uchicago.edu | 7
www.itcon.org | 7
www.ijcnis.org | 7
www.cs.technion.ac.il | 7
orbilu.uni.lu | 7
academicworks.cuny.edu | 7
www.worldscinet.com | 7
journals.tdl.org | 7
lup.lub.lu.se | 7
ppig.org | 7
misq.org | 7
f1000research.com | 7
www.crossref.org | 7
www.bjmc.lu.lv | 7
security-informatics.springeropen.com | 7
www.iieta.org | 7
nime.pubpub.org | 7
www.ijnc.org | 6
pub.uni-bielefeld.de | 6
alexia.lis.uiuc.edu | 6
www.acm.org | 6
www.datenbank-spektrum.de | 6
eu.wiley.com | 6
bulletin.eatcs.org | 6
www.colips.org | 6
www.digra.org | 6
www.teses.usp.br | 6
www.jips-k.org | 6
www.informaworld.com | 6
journal.seriousgamessociety.org | 6
www.clei.org | 6
www.scichina.com | 6
www.euppublishing.com | 6
www.jmis.org | 6
jes-eurasipjournals.springeropen.com | 6
jalc.de | 6
doi.wiley.com | 6
learning-analytics.info | 6
www.macrothink.org | 6
ediss.sub.uni-hamburg.de | 5
ixdea.uniroma2.it | 5
www.springer.com | 5
www.ibai-publishing.org | 5
www.research.att.com | 5
www.info-ab.uclm.es | 5
www.math.md | 5
studia.complexica.net | 5
discovery.ucl.ac.uk | 5
technion.primo.exlibrisgroup.com | 5
www.dpunkt.de | 5
mediatum.ub.tum.de | 5
energyinformatics.springeropen.com | 5
diglib.tugraz.at | 5
amses-journal.springeropen.com | 5
muse.jhu.edu | 5
www.oajaiml.com | 5
ietisy.oxfordjournals.org | 5
superfri.org | 5
asp.eurasipjournals.com | 5
policyreview.info | 5
projecteuclid.org | 5
geo.revuesonline.com | 5
incose.onlinelibrary.wiley.com | 5
jfr.unibo.it | 5
tosc.iacr.org | 5
josis.org | 5
www.sciedu.ca | 5
content.sciendo.com | 5
www.cs.nmsu.edu | 4
www.sav.sk | 4
www.maxwell.vrac.puc-rio.br | 4
ora.ox.ac.uk | 4
weis09.infosecon.net | 4
www.inf.u-szeged.hu | 4
ejournals.wspc.com.sg | 4
subs.emis.de | 4
www.informationr.net | 4
hal.inria.fr | 4
orbit.dtu.dk | 4
www.jmlr.org | 4
rutcor.rutgers.edu | 4
dh2013.unl.edu | 4
perpetualinnovation.net | 4
www.cccg.ca | 4
ippserv.ugent.be | 4
www.jstor.org | 4
urn.fi | 4
www.dh2012.uni-hamburg.de | 4
www.freidok.uni-freiburg.de | 4
ep.liu.se | 4
commons.erau.edu | 4
www.ijpe-online.com | 4
edoc.hu-berlin.de | 4
epub.uni-regensburg.de | 4
www.sne-journal.org | 4
programming-journal.org | 4
telrp.springeropen.com | 4
elbib.ru | 4
pubs.aip.org | 4
journal.iberamia.org | 4
jise.iis.sinica.edu.tw:80 | 3
hss-opus.ub.ruhr-uni-bochum.de | 3
publikationsserver.tu-braunschweig.de | 3
www.computer.org | 3
bookstore.siam.org | 3
www.koreascience.or.kr | 3
ijsdir.sadl.kuleuven.be | 3
oa.upm.es | 3
orbi.uliege.be | 3
cit.srce.hr | 3
elib.tu-darmstadt.de | 3
purl.utwente.nl | 3
www.manchester.ac.uk | 3
trepo.tuni.fi | 3
www.cscan.org | 3
elib.uni-stuttgart.de | 3
imr.sandia.gov | 3
www.mpi-sb.mpg.de | 3
digitool.abdn.ac.uk | 3
dh2010.cch.kcl.ac.uk | 3
vtechworks.lib.vt.edu | 3
opus.bibliothek.uni-wuerzburg.de | 3
archiv.ub.uni-marburg.de | 3
www.bmvc2021-virtualconference.com | 3
publikationen.ub.uni-frankfurt.de | 3
www.imaging.org | 3
cit.fer.hr | 3
informatica.vu.lt | 3
iasks.org | 3
ijdc.net | 3
jnc.psychopen.eu | 3
figshare.com | 3
journals.umcs.pl | 3
www.slejournal.com | 3
academypublisher.com | 3
www.tib-op.org | 3
www.dbpia.co.kr | 3
www.smartcr.org | 3
espace.library.uq.edu.au | 3
publications.aaahq.org | 3
thescipub.com | 3
openjournals.uwaterloo.ca | 3
192.168.10.19 | 3
ejc.revuesonline.com | 3
www.kr.tuwien.ac.at | 2
www.eng.uci.edu | 2
etheses.bham.ac.uk | 2
bulletin.jcdl.org | 2
reference.sabinet.co.za | 2
eldorado.uni-dortmund.de:8080 | 2
www.bcs.org | 2
digitalcommons.dartmouth.edu | 2
tobias-lib.ub.uni-tuebingen.de | 2
madoc.bib.uni-mannheim.de | 2
kais.mines.edu | 2
publications.lib.chalmers.se | 2
vig.pearsoned.com | 2
theses.gla.ac.uk | 2
publikationen.bibliothek.kit.edu | 2
www.fedoa.unina.it | 2
webdoc.sub.gwdg.de | 2
elbib.kpfu.ru | 2
eprints.eemcs.utwente.nl | 2
repositorio.unicamp.br | 2
www.uic.edu | 2
cgm.cs.mcgill.ca | 2
www.ecsi-association.org | 2
bioinformatics.oxfordjournals.org | 2
www.simvis.org | 2
www-formal.stanford.edu | 2
jcse.kiise.org | 2
www.db-thueringen.de | 2
dx.doi.org | 2
mlg07.dsi.unifi.it | 2
www.scit.wlv.ac.uk | 2
www.base-search.net | 2
www.deeplearningbook.org | 2
eprints.soton.ac.uk | 2
wrap.warwick.ac.uk | 2
tau.primo.exlibrisgroup.com | 2
nips.djvuzone.org | 2
swb2.bsz-bw.de | 2
e-pub.uni-weimar.de | 2
sro.sussex.ac.uk | 2
geb.uni-giessen.de | 2
kluedo.ub.rptu.de | 2
www.mulberrytech.com | 2
www.opus.ub.uni-erlangen.de | 2
uncertainty99.microsoft.com | 2
danae.uni-muenster.de | 2
store.elsevier.com | 2
dspace.library.uu.nl | 2
colt2008.cs.helsinki.fi | 2
elib.ub.uni-osnabrueck.de | 2
dl.kr.org | 2
www.repo.uni-hannover.de | 2
bieson.ub.uni-bielefeld.de | 2
hal-emse.ccsd.cnrs.fr | 2
www.dspace.cam.ac.uk | 2
proceedings.bmvc2023.org | 2
opus.bath.ac.uk | 2
urlib.net | 2
dspace.mit.edu | 2
ctw2011.dia.uniroma3.it | 2
grammars.grlmc.com | 2
utpjournals.press | 2
docs.lib.purdue.edu | 2
adb.sagepub.com | 2
todigra.org | 2
www.journalofcloudcomputing.com | 2
www.scielo.cl | 2
escholarship.org | 2
www.almob.org | 2
amc-journal.eu | 2
journals.vilniustech.lt | 2
journals.agh.edu.pl | 2
slejournal.springeropen.com | 2
www.scielo.br | 2
arima.episciences.org | 2
infedu.vu.lt | 2
csimq-journals.rtu.lv | 2
www.ijfis.org | 2
nowpublishers.com | 2
www.informingscience.org | 2
eldorado.tu-dortmund.de | 2
decisionanalyticsjournal.springeropen.com | 2
jaec.vn | 2
www.aicit.org | 2
rig.revuesonline.com | 2
journal.info.unlp.edu.ar | 2
crl.acrl.org | 2
oops.uni-oldenburg.de | 1
doktori.hu | 1
ftp.cs.uregina.ca | 1
european-lisp-symposium.org | 1
decsai.ugr.es | 1
papers.ssrn.com | 1
www.cs.helsinki.fi | 1
web.stanford.edu | 1
repository.royalholloway.ac.uk | 1
e-collection.library.ethz.ch | 1
tede2.pucrs.br | 1
kups.ub.uni-koeln.de | 1
bura.brunel.ac.uk | 1
aima.cs.berkeley.edu | 1
gala.gre.ac.uk | 1
scholar.uwindsor.ca | 1
www-i2.informatik.rwth-aachen.de | 1
psb.stanford.edu | 1
www.eg.org | 1
clok.uclan.ac.uk | 1
computer.org | 1
www.elsevier.com | 1
elib.suub.uni-bremen.de | 1
ub-madoc.bib.uni-mannheim.de | 1
www.webology.org | 1
ejlt.org | 1
ci-journal.net | 1
journals.hil.unb.ca | 1
www.scfbm.org | 1
archiv.ub.uni-heidelberg.de | 1
kclpure.kcl.ac.uk | 1
openaccess.city.ac.uk | 1
www.search-engines-book.com | 1
athene-forschung.unibw.de | 1
w210.ub.uni-tuebingen.de | 1
dr.nsk.hr | 1
www.mii.lt | 1
dspace.library.uvic.ca | 1
bookstore.ams.org | 1
refubium.fu-berlin.de | 1
www-users.cs.umn.edu | 1
dream.inf.ed.ac.uk | 1
www.cs.virginia.edu | 1
eprints.bournemouth.ac.uk | 1
www.semantic-web-book.org | 1
cs.uwaterloo.ca | 1
epubs.surrey.ac.uk | 1
web.cecs.pdx.edu | 1
ubt.opus.hbz-nrw.de | 1
uvka.ubka.uni-karlsruhe.de | 1
www.diss.fu-berlin.de | 1
tez.yok.gov.tr | 1
www.doc.ic.ac.uk | 1
www.jthtl.org | 1
ijcopi.org | 1
www.wiley.com | 1
www.cs.waikato.ac.nz | 1
pi.informatik.uni-siegen.de | 1
www.shaker.de | 1
www.unioviedo.es | 1
ftp.inria.fr | 1
purl.flvc.org | 1
www.ijdc.net | 1
ibook.ics.uci.edu | 1
www.upress.uni-kassel.de | 1
edoc.bibliothek.uni-halle.de | 1
eprints.lancs.ac.uk | 1
www.lix.polytechnique.fr | 1
repository.tudelft.nl | 1
logos-verlag.de | 1
docserv.uni-duesseldorf.de | 1
elpub.architexturez.net | 1
pub-data.leuphana.de | 1
dup.oa.hhu.de | 1
netfiles.uiuc.edu | 1
periodicos.ufmg.br | 1
etheses.dur.ac.uk | 1
www.informatik.uni-freiburg.de | 1
dspace.library.uu.nl:8080 | 1
dspace.ub.uni-siegen.de | 1
www.isi.edu | 1
boris.unibe.ch | 1
inex.mpi-inf.mpg.de | 1
digitalcommons.usf.edu | 1
www.dbs.ifi.lmu.de | 1
hsss.slub-dresden.de | 1
ftp.cs.man.ac.uk | 1
www.aiml.net | 1
www.webdragons.net | 1
eldiss.uni-kiel.de | 1
www.almaden.ibm.com | 1
www.repository.cam.ac.uk | 1
lrec-conf.org | 1
eprints.nottingham.ac.uk | 1
net2.shams.edu.eg | 1
www.cuvillier.de | 1
ftp.elis.rug.ac.be | 1
repositorio.ufpe.br | 1
www.iajit.org | 1
nbn-resolving.de | 1
www.pearson-studium.de | 1
hydra.hull.ac.uk | 1
archive-ouverte.unige.ch | 1
web.archive.org | 1
www.addison-wesley.de | 1
www.elsevierdirect.com | 1
www.edbt2000.uni-konstanz.de | 1
www-users.cse.umn.edu | 1
ijsdir.jrc.ec.europa.eu | 1
wwwiti.cs.uni-magdeburg.de | 1
kola.opus.hbz-nrw.de | 1
deposit.fernuni-hagen.de | 1
tumb1.biblio.tu-muenchen.de | 1
dl.mensch-und-computer.de | 1
biblio.ugent.be | 1
www.info.uaic.ro | 1
www-rocq.inria.fr | 1
www.bd.bibl.ita.br | 1
dline.info | 1
jwcn.eurasipjournals.com | 1
www.learning-analytics.info | 1
10.1.18.161 | 1
www.discuss.wmie.uz.zgora.pl | 1
logcom.oupjournals.org | 1
iti.srce.unizg.hr | 1
smartcr.org | 1
www.firstmonday.org | 1
library.gito.de | 1
bookstore.teri.res.in | 1
glottometrics.iqla.org | 1
www.jasss.org | 1
repository.publisso.de | 1
www.itc.ktu.lt | 1
www.ssrn.com | 1
misq.umn.edu | 1
fdslive.oup.com | 1
publications.eai.eu | 1
cmsr14.cs.mcgill.ca | 1
gispoint.de | 1
wer.inf.puc-rio.br | 1
www.emisa-journal.org | 1
sciendo.com | 1
www.iasks.org | 1
www.amses-journal.com | 1
www.aimspress.com | 1
clei.org | 1
jdssv.org | 1
hfs.sagepub.com | 1
jamia.oxfordjournals.org | 1
jclinbioinformatics.biomedcentral.com | 1



</body>

</html>

**Comment by melisabok** [comment]
thanks for the status @xkopenreview ! I would like to use the dev site to test the DBLP upload using the process functions, could we do that?

**Pull request merged**
