### PR TITLE
Fix/Add a local chrome binary as fallback

### PR DESCRIPTION
**Pull request by xkopenreview**
this pr should add a chrome binary (Version: 122.0.6261.128 (r1250580), for linux64) as fallback when puppeteer fail to launch the browser it downloaded

~~this version purposely throw an error when launching browser instance to trigger the local bindary~~
~~it should be removed after testing on server~~

### CODE REVIEW

**Comment by xkopenreview** [comment]
for some unknown reason the test will get stuck in github actions when manually throwing error in launching browser
executed tests on Harold's machine (with throw error) and all passed

**Comment by xkopenreview** [comment]
user may need to install git-lfs extension (https://git-lfs.com/) because chrome is over 100mb

**Comment by carlosmondra** [comment]
Oh I didn't imagine that the image was going to be that big. I thought it was going to be less than 10mb. Maybe we should download it separately then. I don't think we should commit it to any repo. So do the same thing we do with openreview-py for the firefox driver.

**Comment by xkopenreview** [comment]
i checked the failed download url in 
https://github.com/openreview/openreview-js/actions/runs/8007918188/job/21873766049
again and it's working now 
the download failure might be a temporary issue
so a local fallback may not be required

**Comment by xkopenreview** [comment]
fix of client test has been added to #28 
and decided to use cloud function for extraction so close

**Pull request closed without merging**
